---
- name: Install default Apache
  hosts: test
  become: yes
  
  vars:
    source_file: /root/myansible/index.html
    dest_file: /var/www/html
    service_list:
      - { service: http, state: disabled }
      - { service: https, state: disabled }

  tasks: 
    - name: yum remove Apache
      yum: name=httpd state=absent
      
    #- name: State Apache and Enable it on test servers
    #  service: name=httpd state=started enabled=yes

    - name: Remove index.html file
      file: path='/var/www/html/index.html' state=absent
      notify: Restart Apache
    
    - name: Close firewalld ports
      firewalld:
        service: "{{ item.service }}"
        permanent: true
        state: "{{ item.state }}"
      loop: "{{ service_list }}"
      notify: Restart Firewalld
  
  handlers:
    - name: Restart Apache
      service: name=httpd state=restarted
    - name: Restart Firewalld
      service: name=firewalld state=restarted
