---
- name: Install default Apache
  hosts: test
  become: yes
  
  tasks: 
    - name: yum install Apache
      yum: name=httpd state=latest
      
    - name: State Apache and Enable it on test servers
      service: name=httpd state=started enabled=yes
