---
- name: Remove default Apache
  hosts: test
  become: true

  vars:
    service_list:
      - {service: http, state: disabled}
      - {service: https, state: disabled}

  tasks:
    - name: Remove index.html file
      file: path='/var/www/html/index.html' state=absent

    - name: apt remove Apache
      apt: name=apache2 state=absent

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
    - name: Restart Firewalld
      service: name=firewalld state=restarted
