---
# tasks file for install_my_apache

- name: yum install Apache
  yum: name=httpd state=latest
  
- name: State Apache and Enable it on test servers
  service: name=httpd state=started enabled=yes

- name: Upload index.html file
  copy: src=index.html dest={{ dest_file }} mode=0555
  notify: Restart Apache

- name: Open firewalld ports
  firewalld:
    service: "{{ item.service }}"
    permanent: true
    state: "{{ item.state }}"
  loop: "{{ service_list }}"
  notify: Restart Firewalld